### ISSUE TITLE
Command line argument for file should be optional

### ISSUE THREAD

**Issue by jrdemasi** [faisalmlalani/Lalani_Trang_Jones_CSCI2270_FinalProject#2]
Requiring an empty text file to exist just to run a program seems silly and inefficient.  Proposed: Add a check to see # of arguments, if # of arguments > 1, parse file to get saved cards, if <=1, do nothing.  If no input is provided and cards are added and saved, the file can be created.

**Comment by faisalmlalani** [comment]
I wouldn't go as far as to call it silly, but I agree with what you're saying. Will be added in next push. Thanks!
